services:
  frontend:
    image: ghcr.io/medyasine/dental-fe:latest
    container_name: dental-frontend
    ports:
      - "8080:80"
    restart: unless-stopped
  backend:
    image: ghcr.io/medyasine/dental-be:latest
    container_name: dental-backend
    ports:
      - "8081:8080"
    restart: unless-stopped