services:
  db:
    image: postgres:16-alpine
    container_name: dpms-postgres
    environment:
      POSTGRES_DB: dpms
      POSTGRES_USER: dpms
      POSTGRES_PASSWORD: dpms
    ports:
      - "5433:5432"
    volumes:
      - dpms_pgdata:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  dpms_pgdata:
